[package]
name = "innocamp-backend"
version = "0.1.0"
authors = ["omega-800 <gshevoroshkin@gmail.com>"]
edition = "2024"

[dependencies]
actix-web = "4.12.1"
async-graphql = "7.2.1"
async-graphql-actix-web = "7.2.1"
uuid = { version = "1.20.0", features = ["v4"] }
